services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn BlogApp.wsgi:application --bind 0.0.0.0:8000 --workers=2 -t 40 --access-logfile -  --access-logformat '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" %(M)s'
    volumes:
      - statics_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 8000:8000
    expose:
      - 8000
    links:
      - redis:redis
    env_file: .env
    restart: unless-stopped
    depends_on:
      - postgres

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A BlogApp worker -l info -c 2
    volumes:
      - statics_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    links:
      - redis:redis
    env_file: .env
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres
    shm_size: 512mb
    ports:
      - 5432
    env_file:
      - .env.postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
    restart: unless-stopped

  redis:
    image: redis:latest
    expose:
      - 6379
    restart: unless-stopped

volumes:
  postgres-volume:
  statics_volume:
  media_volume:
